name: 'dbt_snowflake_analytics'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_snowflake_analytics:
    staging:
      +materialized: view
      +database: DBT
      +schema: SILVER

    intermediate:
      +materialized: view
      +database: DBT
      +schema: SILVER

    marts:
      +materialized: table
      +database: DBT
      +schema: GOLD

seeds:
  dbt_snowflake_analytics:
    +database: DBT
    +schema: BRONZE
    +quote_columns: false

snapshots:
  dbt_snowflake_analytics:
    +target_database: DBT
    +target_schema: AUDIT